= Kết luận và kiến nghị

== Những đóng góp của khóa luận

Khóa luận đã chuyển PULSE-7B từ một mô hình hỏi–đáp thị giác sinh văn bản thành một bộ phân lớp bệnh tim đa nhãn có khả năng phân biệt tốt trên PTB-XL, bằng một giải pháp tối giản không sửa lõi: phân rã ba tác vụ đúng cấu trúc PTB-XL @pulse @strodthoff, tách quy tắc nhãn để cứu nhóm nhịp/hình thái @wagner, trở về entropy chéo next-token nguyên gốc, và chỉ tinh chỉnh mô hình ngôn ngữ bằng QLoRA trên nhánh thị giác đông cứng. Giao thức đánh giá teacher-forced là đóng góp về phương pháp: nó cho phép đo macro-AUC không phụ thuộc ngưỡng một cách nhất quán và tái lập trên các lớp có mẫu dương, tách chất lượng phân biệt khỏi sự mong manh của khâu sinh tự do. Kết quả trung bình macro-AUC 0.876 trên tập kiểm thử độc lập fold-10, vượt mô hình nền PULSE-7B +0.097 trong so sánh có kiểm soát, cho thấy một mô hình ngôn ngữ–thị giác có thể phân biệt bệnh tim đa nhãn từ ảnh ECG với khả năng phân biệt tốt mà không cần đến tín hiệu một chiều. Khi đưa về đúng phân nhóm Super 5 lớp mà PULSE công bố (Mục 4.3), pipeline của khóa luận tái lập gần như khớp con số gốc trên chính PULSE-7B (macro-AUC 0.826 so với 0.824 trong bài báo), xác nhận quy trình đánh giá trung thực; và mô hình đề xuất đạt macro-AUC 0.902 trên cùng phân nhóm này — vượt số công bố của PULSE trên chính benchmark của họ.

Cần nêu rõ giới hạn của kết luận này: macro-AUC đo khả năng XẾP HẠNG/PHÂN BIỆT (model gán điểm cao hơn cho mẫu dương so với mẫu âm), chứ không đồng nghĩa với một bộ phân lớp đã hiệu chuẩn sẵn sàng triển khai. macro-F1 ở mức ngưỡng cố định còn thấp (trung bình 0.26), phản ánh đặc thù phân phối dài đuôi và việc lựa chọn ngưỡng cho lớp hiếm còn khó; do đó khóa luận KHÔNG khẳng định một hệ chẩn đoán lâm sàng sẵn dùng, mà chỉ chứng minh tính khả thi về phân biệt đa nhãn và sự cải thiện có kiểm soát so với mô hình nền. Phân tích lâm sàng trên 5 siêu lớp (Mục 4.3) cho thấy độ đặc hiệu và NPV cao (macro 0.89 và 0.92) nhưng độ nhạy còn hạn chế ở một số nhóm — thấp nhất là phì đại HYP chỉ 0.42 (bỏ sót quá nửa số ca) — nên ở khía cạnh quan trọng nhất với lâm sàng là không bỏ sót bệnh, mô hình chưa đạt ngưỡng tin cậy. Hiệu chuẩn xác suất, chọn điểm vận hành theo bất đối xứng chi phí để nâng độ nhạy lớp hiếm, đóng băng ngưỡng trên tập kiểm định độc lập và đánh giá đa fold là các bước cần thiết trước khi nói tới độ tin cậy lâm sàng.

== Hướng phát triển

=== Hướng nghiên cứu

Huấn luyện thêm epoch để khai thác dư địa còn lại, vì hiệu năng vẫn tăng từ epoch 1 sang epoch 2; bổ sung giám sát lập luận (reasoning) theo tinh thần LLaVA-Med @llavamed và dữ liệu hỏi–đáp ECG @ecgqa để mô hình không chỉ xuất nhãn mà còn sinh lập luận có căn cứ; khảo sát kỹ hơn các biến thể tái trọng số cân bằng lớp @cui; và đánh giá đa fold để khẳng định khả năng tổng quát hóa. Riêng hướng giám sát lập luận, cần điền khối `[REASONING]` hiện để trống (Mục 3.3) bằng văn diễn giải sinh kèm — ví dụ tổng hợp từ siêu dữ liệu PTB-XL — nhưng vẫn GIỮ khối nhãn số `code: 0|1` đặt sau nó. Cách kết hợp này khác với việc nhúng nhãn vào báo cáo văn xuôi thuần kiểu PULSE: giữ khối số là điều kiện để vẫn đọc được xác suất từng lớp và đo macro-AUC không phụ thuộc ngưỡng, đồng thời có thêm phần diễn giải; thách thức chính là bảo đảm chất lượng văn diễn giải sinh tự động để không huấn luyện mô hình bằng lập luận sai.

Một hướng cải tiến cụ thể về đầu vào thị giác là nâng độ phân giải tiling. Như đã phân tích ở Mục 3.2.1, cấu hình anyres hiện tại thu nhỏ ảnh 1344×672 về 672×336 (lưới 2×1, 1728 token), làm mất chi tiết tinh của tín hiệu (sóng P, đoạn ST). Trong giới hạn cửa sổ ngữ cảnh 4096 token, có thể chuyển sang lưới mịn hơn vẫn lọt ngân sách — chẳng hạn 2×2 hoặc 4×1 (khoảng 2880 token) — để giữ chi tiết tốt hơn; riêng lưới 4×2 đầy đủ (9 ô, 5184 token) vượt quá 4096 và đòi hỏi mở rộng cửa sổ ngữ cảnh (ví dụ RoPE scaling) kèm huấn luyện lại. Việc khảo sát đánh đổi giữa độ phân giải đầu vào và chi phí ngữ cảnh được để ngỏ như một hướng phát triển có tiềm năng nâng cao hiệu năng. Một hướng kiểm chứng khác liên quan tới định dạng ảnh: khóa luận thêm một dải nhịp chuyển đạo II 10 giây mà bài báo PULSE không sử dụng (Bảng 3.1); đóng góp riêng của dải nhịp này nên được tách bằng một nghiên cứu cắt bỏ (render có và không có dải nhịp) để xác nhận nó thực sự giúp ích chứ không chỉ là một sai lệch khỏi phân phối huấn luyện của mô hình nền.

=== Hướng ứng dụng

Hoàn thiện pipeline thành công cụ hỗ trợ đọc ECG đa nhãn trực tiếp từ ảnh, tích hợp giao diện cho bác sĩ và mở rộng so sánh có kiểm soát với cả baseline đơn phương thức @strodthoff lẫn các phương pháp đa phương thức @pulse @gem.
